/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import model.Conjunto;
import model.Elemento;

/**
 *
 * @author Aluno
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        jcbConjunto1.removeAllItems();
        jcbConjunto2.removeAllItems();
        jcbConjunto1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent event) {
                //Expressoes regulares
                Pattern acharConjunto = Pattern.compile("[A-Z]");

                if (!(jcbConjunto1.getSelectedItem() == null)) {
                    String select1 = (String) jcbConjunto1.getSelectedItem();
                    String select2 = (String) jcbConjunto2.getSelectedItem();
                    Matcher acharConjuntoMatcher1 = acharConjunto.matcher(select1);
                    Matcher acharConjuntoMatcher2 = acharConjunto.matcher(select2);

                    if (acharConjuntoMatcher1.find()) {
                        //achou conjunto
                        jbPertence.setEnabled(false);
                        jbNaoPertence.setEnabled(false);
                    } else {
                        //achou elemento
                        jbPertence.setEnabled(true);
                        jbNaoPertence.setEnabled(true);
                    }
                    if (acharConjuntoMatcher2.find()) {
                        //achou conjunto
                        jbPertence.setEnabled(true);
                        jbNaoPertence.setEnabled(true);
                    } else {
                        //achou elemento
                        jbPertence.setEnabled(false);
                        jbNaoPertence.setEnabled(false);
                    }
                }

            }
        });
        jcbConjunto2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent event) {
                //Expressoes regulares
                Pattern acharConjunto = Pattern.compile("[A-Z]");

                if (!(jcbConjunto2.getSelectedItem() == null)) {
                    String select1 = (String) jcbConjunto1.getSelectedItem();
                    String select2 = (String) jcbConjunto2.getSelectedItem();
                    Matcher acharConjuntoMatcher1 = acharConjunto.matcher(select1);
                    Matcher acharConjuntoMatcher2 = acharConjunto.matcher(select2);

                    if (acharConjuntoMatcher1.find()) {
                        //achou conjunto
                        jbPertence.setEnabled(false);
                        jbNaoPertence.setEnabled(false);
                    } else {
                        //achou elemento
                        jbPertence.setEnabled(true);
                        jbNaoPertence.setEnabled(true);
                    }
                    if (acharConjuntoMatcher2.find()) {
                        //achou conjunto
                        jbPertence.setEnabled(true);
                        jbNaoPertence.setEnabled(true);
                    } else {
                        //achou elemento
                        jbPertence.setEnabled(false);
                        jbNaoPertence.setEnabled(false);
                    }
                }

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jbArquivo = new javax.swing.JButton();
        jtfArquivo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jbContidoOuIgual = new javax.swing.JButton();
        lbNaoContidoOuIgual = new javax.swing.JButton();
        lbContidoPropriamente = new javax.swing.JButton();
        lbNaoContidoPropriamente = new javax.swing.JButton();
        jbUniao = new javax.swing.JButton();
        jbIntersecao = new javax.swing.JButton();
        lbProdutoCartesiano = new javax.swing.JButton();
        lblOperacoes = new javax.swing.JLabel();
        jbPertence = new javax.swing.JButton();
        jbNaoPertence = new javax.swing.JButton();
        jcbConjunto1 = new javax.swing.JComboBox();
        jcbConjunto2 = new javax.swing.JComboBox();
        jlSeta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jbArquivo.setText("Pesquisar...");
        jbArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbArquivoActionPerformed(evt);
            }
        });

        jtfArquivo.setEnabled(false);
        jtfArquivo.setName(""); // NOI18N
        jtfArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfArquivoActionPerformed(evt);
            }
        });

        jbContidoOuIgual.setText("⊆");

        lbNaoContidoOuIgual.setText("!⊆");

        lbContidoPropriamente.setText("⊂");
        lbContidoPropriamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbContidoPropriamenteActionPerformed(evt);
            }
        });

        lbNaoContidoPropriamente.setText("!⊂");

        jbUniao.setText("∪");
        jbUniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUniaoActionPerformed(evt);
            }
        });

        jbIntersecao.setText("∩");

        lbProdutoCartesiano.setText("×");

        lblOperacoes.setText("Operações:");

        jbPertence.setText("∈");
        jbPertence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPertenceActionPerformed(evt);
            }
        });

        jbNaoPertence.setText("!∈");

        jcbConjunto1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jcbConjunto1, org.jdesktop.beansbinding.ObjectProperty.create(), jcbConjunto1, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);

        jcbConjunto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbConjunto1ActionPerformed(evt);
            }
        });

        jcbConjunto2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jcbConjunto2, org.jdesktop.beansbinding.ObjectProperty.create(), jcbConjunto2, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);

        jcbConjunto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbConjunto2ActionPerformed(evt);
            }
        });

        jlSeta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlSeta.setText("->");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbContidoOuIgual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNaoContidoOuIgual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbIntersecao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbContidoPropriamente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNaoContidoPropriamente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbProdutoCartesiano))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbPertence)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOperacoes)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbNaoPertence)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbUniao))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcbConjunto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlSeta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbConjunto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbConjunto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbConjunto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlSeta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOperacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPertence)
                    .addComponent(jbNaoPertence)
                    .addComponent(jbUniao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbContidoOuIgual)
                    .addComponent(lbNaoContidoOuIgual)
                    .addComponent(jbIntersecao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbContidoPropriamente)
                    .addComponent(lbNaoContidoPropriamente)
                    .addComponent(lbProdutoCartesiano)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbArquivo)
                .addComponent(jtfArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbArquivo)
                    .addComponent(jtfArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbArquivoActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Filtro .txt", "txt"));
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.showOpenDialog(this);

        File txtFileLer = new File(fileChooser.getSelectedFile().getAbsolutePath());
        jtfArquivo.setText(txtFileLer.getName());

        // Listas para receber os objetos
        ArrayList<Conjunto> conjuntos = new ArrayList<>();
        ArrayList<Elemento> elementos = new ArrayList<>();

        // Leitura do arquivo
        try {
            FileReader arq = new FileReader(txtFileLer);
            BufferedReader lerArq = new BufferedReader(arq);
            // Pegando linhas do arquivo
            String linha = lerArq.readLine();

            //Expressoes regulares
            Pattern acharConjunto = Pattern.compile("[A-Z]");
            Pattern acharElemento = Pattern.compile("([a-z])");
            Pattern numero = Pattern.compile("\\d+");

            // Varrendo as linhas
            while (linha != null) {
                // Aplicando regex
                Matcher acharConjuntoMatcher = acharConjunto.matcher(linha);
                Matcher acharElementoMatcher = acharElemento.matcher(linha);
                Matcher numeroMatcher = numero.matcher(linha);

                Conjunto target = new Conjunto();
                Elemento shot = new Elemento();
                System.out.print("\n");
                // Econtrando conjuntos
                if (acharConjuntoMatcher.find()) {
                    // Nome do conjunto
                    String nome = acharConjuntoMatcher.group();
                    // Instancia objeto e adiciona ao ArrayList
                    conjuntos.add(new Conjunto(nome));
                    System.out.print("conjunto " + nome + " -> ");
                    while (numeroMatcher.find()) {
                        // Obtém valor
                        int value = Integer.parseInt(numeroMatcher.group());
                        Elemento elemento = new Elemento(value);
                        target.addElemento(elemento);
                        System.out.print(elemento.getElemento() + " ");
                    }
                    // TESTE DE OBJETO
                    target = encontraConjunto(nome, conjuntos);
                    System.out.print("objeto: " + target.getNome());
                }
                // Encontrando elementos
                if (acharElementoMatcher.find()) {
                    // Nome do elemento
                    String nome = acharElementoMatcher.group();
                    System.out.print("elemento " + nome + " -> ");
                    int value = 0;
                    // O loop pegará o elemento com 1 ou mais digitos.
                    while (numeroMatcher.find()) {
                        value = Integer.parseInt(numeroMatcher.group());
                    }
                    // Instancia e adiciona ao ArrayList
                    System.out.print(value + " ");
                    elementos.add(new Elemento(nome, value));
                    // TESTE DO OBJETO
                    shot = encontraElemento(nome, elementos);
                    System.out.print("objeto: " + shot.getNome());
                }
                linha = lerArq.readLine(); // lê da segunda até a última linha
            }

            arq.close();
        } catch (IOException e) {
            System.err.printf("Erro na abertura do arquivo: %s.\n",
                    e.getMessage());
        }
        // PREENCHER O COMBOBOX
        for (Conjunto obj : conjuntos) {
            jcbConjunto1.addItem(obj.getNome());
        }
        for (Elemento obj : elementos) {
            jcbConjunto1.addItem(obj.getNome());
        }
        for (Conjunto obj : conjuntos) {
            jcbConjunto2.addItem(obj.getNome());
        }
        for (Elemento obj : elementos) {
            jcbConjunto2.addItem(obj.getNome());
        }
        System.out.println();
    }//GEN-LAST:event_jbArquivoActionPerformed

    private void jtfArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfArquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfArquivoActionPerformed

    private void jbUniaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUniaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbUniaoActionPerformed

    private void jcbConjunto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbConjunto1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jcbConjunto1ActionPerformed

    private void jcbConjunto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbConjunto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbConjunto2ActionPerformed

    private void jbPertenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPertenceActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jbPertenceActionPerformed

    private void lbContidoPropriamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbContidoPropriamenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbContidoPropriamenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    public Conjunto encontraConjunto(String nome, ArrayList<Conjunto> lista) {
        Conjunto target = new Conjunto();
        for (Conjunto obj : lista) {
            if (obj.getNome() == nome) {
                target = obj;
            }
        }
        return target;
    }

    public Elemento encontraElemento(String nome, ArrayList<Elemento> lista) {
        Elemento target = new Elemento();
        for (Elemento obj : lista) {
            if (obj.getNome() == nome) {
                target = obj;
            }
        }
        return target;
    }

    public ArrayList<String> retornaNomesConjuntos(ArrayList<Conjunto> lista) {
        ArrayList<String> nomes = new ArrayList();
        for (Conjunto obj : lista) {
            nomes.add(obj.getNome());
        }
        return nomes;
    }

    public ArrayList<String> retornaNomesElementos(ArrayList<Elemento> lista) {
        ArrayList<String> nomes = new ArrayList();
        for (Elemento obj : lista) {
            nomes.add(obj.getNome());
        }
        return nomes;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbArquivo;
    private javax.swing.JButton jbContidoOuIgual;
    private javax.swing.JButton jbIntersecao;
    private javax.swing.JButton jbNaoPertence;
    private javax.swing.JButton jbPertence;
    private javax.swing.JButton jbUniao;
    private javax.swing.JComboBox jcbConjunto1;
    private javax.swing.JComboBox jcbConjunto2;
    private javax.swing.JLabel jlSeta;
    private javax.swing.JTextField jtfArquivo;
    private javax.swing.JButton lbContidoPropriamente;
    private javax.swing.JButton lbNaoContidoOuIgual;
    private javax.swing.JButton lbNaoContidoPropriamente;
    private javax.swing.JButton lbProdutoCartesiano;
    private javax.swing.JLabel lblOperacoes;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
